export const SPECIALIZATIONS = [
    "General Medicine",
    "Pediatrics",
    "Dermatology",
    "Psychiatry",
    "Radiology",
    "Pathology",
    "Anesthesiology",
    "Pulmonology",
    "Cardiology",
    "Endocrinology",
    "Neurology",
    "Gastroenterology",
    "Nephrology",
    "Hematology",
    "General Surgery",
    "Orthopedics",
    "ENT (Otorhinolaryngology)",
    "Ophthalmology",
    "Obstetrics & Gynecology (OBG)",
    "Urology",
    "Neurosurgery",
    "Cardiothoracic Surgery",
    "Plastic Surgery",
    "Ayurveda",
    "Homeopathy",
    "Unani",
    "Naturopathy"
]